### ISSUE TITLE
error in voting using command line

### ISSUE THREAD

**Issue by btcre** [xeroc/piston-cli#91]
Hi,
I'm getting an error in voting, before it works okay.  
After the node connection problem I upgraded the piston and now this is the error in voting.
---

**piston upvote --voter btcre @irawandedy/make-sticky-rice-bulukat-acehnese-and-wrapping-techniques**

Traceback (most recent call last):
  File "/home/btcre/.local/bin/piston", line 11, in <module>
    sys.exit(main())
  File "/home/btcre/.local/lib/python3.5/site-packages/steem_piston-0.3-py3.5.egg/piston/__main__.py", line 833, in main
    voter=args.voter
  File "/home/btcre/.local/lib/python3.5/site-packages/steem_piston-0.3-py3.5.egg/piston/steem.py", line 529, in vote
    return self.executeOp(op, wif)
  File "/home/btcre/.local/lib/python3.5/site-packages/steem_piston-0.3-py3.5.egg/piston/steem.py", line 340, in executeOp
    tx = transactions.JsonObj(tx)
AttributeError: module 'steembase.transactions' has no attribute 'JsonObj'

**Comment by xeroc** [comment]
That is weird, it shouldn't happen, can you please run

    pip3 install steem-piston --upgrade

to make sure the dependencies are updated aswell?

**Comment by btcre** [comment]
Ok upgraded, I got the same error message.

**Comment by xeroc** [comment]
hmm .. well .. the most recent version of piston doesn't use piston/steem.py .. 
something must be weird with your installation.

can you try to uninstall with `pip3 uninstall steem-piston` first?

**Comment by btcre** [comment]
Hi Xeroc,
I unstalled and then installed it again, but once I run piston command I
got this error message

Traceback (most recent call last):
  File "/home/btcre/.local/bin/piston", line 7, in <module>
    from piston.__main__ import main
  File "/home/btcre/.local/lib/python3.5/site-packages/piston/__main__.py",
line 40, in <module>
    from steem.steem import AccountDoesNotExistsException
ImportError: cannot import name 'AccountDoesNotExistsException'

**Comment by btcre** [comment]
Hi,
I reinstall my server and reinstall piston and upgraded, every piston commands works fine except to the vote command, this is the new error I'm getting, please need feedback and thank you.

--
Traceback (most recent call last):
  File "/home/btcre/.local/bin/piston", line 11, in <module>
    sys.exit(main())
  File "/home/btcre/.local/lib/python3.5/site-packages/pistoncli/__main__.py", line 1533, in main
    post = Post(args.post)
  File "/home/btcre/.local/lib/python3.5/site-packages/piston/post.py", line 47, in __init__
    self.refresh()
  File "/home/btcre/.local/lib/python3.5/site-packages/piston/post.py", line 81, in refresh
    Amount(post.get("total_pending_payout_value", "0 %s" % self.steem.symbol("SBD")))
  File "/home/btcre/.local/lib/python3.5/site-packages/piston/amount.py", line 59, in __add__
    assert other["asset"] == self["asset"]
AssertionError

**Comment by xeroc** [comment]
Yhea .. the backend has changed a couple things and I coudn't catch up .. please install piston-cli 0.5.1(!)
