### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by williambanks** [xeroc/piston-cli#94]
>piston --help
Traceback (most recent call last):
  File "/home/user/.local/bin/piston", line 7, in <module>
    from piston.__main__ import main
  File "/home/user/.local/lib/python3.5/site-packages/piston/__main__.py", line 11, in <module>
    from steem.storage import configStorage as config
  File "/home/user/.local/lib/python3.5/site-packages/steem/__init__.py", line 2, in <module>
    from .steem import Steem
  File "/home/user/.local/lib/python3.5/site-packages/steem/steem.py", line 1, in <module>
    from piston.steem import Steem as PistonSteem
  File "/home/user/.local/lib/python3.5/site-packages/piston/steem.py", line 2, in <module>
    from steem.steem import Steem as SteemSteem
ImportError: cannot import name 'Steem'

Fresh install followed instructions here, and also had to install openssl development libraries which weren't specified.

**Comment by williambanks** [comment]
https://piston.readthedocs.io/en/stable/installation.html#install-with-pip

**Comment by xeroc** [comment]
please use `pip3 install piston-cli` instead

uninstall the `steem-piston` package first: `pip3 uninstall steem-piston`
